version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    ports:
      - '${DATABASE_PORT}:3306'
    expose:
      - '${DATABASE_PORT}'
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
