export const enum ENV {
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION',
}

export const TOKEN_SYMBOL_CHAR_LENGTH = 8;
export const INT_11_MAX = 2147483647;
